### ISSUE TITLE
Link to this on archives.gov/developer

### ISSUE THREAD

**Issue by gbinal** [usnationalarchives/Catalog-API#1]
Please add a link for this API on the NARA developer hub.  I went looking for it there and didn't find it.

**Comment by Dominic-MP** [comment]
You're quite right, that page is out of date. @mereastew: presumably, the catalog API should be right at the top of http://www.archives.gov/developer/#api now?

**Comment by mereastew** [comment]
Yup. I'll work on getting that up today.  Thanks!

Meredith Stewart
Office of Innovation
National Archives and Records Administration
meredith.stewart@nara.gov
301.837.1780

**Comment by Dominic-MP** [comment]
Completed! http://www.archives.gov/developer/#api

**Comment by mereastew** [comment]
We've got it up now here: http://www.archives.gov/developer/#api
