### ISSUE TITLE
Searching with parent NAID

### ISSUE THREAD

**Issue by awasgreen** [usnationalarchives/Catalog-API#16]
I'm trying to query a search with the API using the parent NAID, but I get the error message "f.parentNaId - is not allowed." 

Any help? If this field isn't incorporated into the API does anyone have a good work around.

**Comment by DominicBM** [comment]
> I'm trying to query a search with the API using the parent NAID, but I get the error message "f.parentNaId - is not allowed."
> 
> Any help? If this field isn't incorporated into the API does anyone have a good work around.

It sounds like you found `f.parentNaId` from the web search URL parameters, but the API doesn't really use these types of parameters. In the API, you can generally do fielded search on any metadata field found in actual records, so the best way to see how to search on these fields is to look at a full record and that will show you all the field names and how to specify the path for any field. For example:

https://catalog.archives.gov/api/v1?naIds=5950850

In the JSON, you will see a `parentSeries` object. So, the field path to search on the parent series NAIDs, you would search on `description.fileUnit.parentSeries`:

https://catalog.archives.gov/api/v1?description.fileUnit.parentSeries=5756466

Note that unlike the search interface, there isn't strictly a way to search on all parent NAIDs at once, as such. If you are searching on series with a specified parent record group or collection, you can still do this in one query—but if you want all records with a parent series, you have to actually query `description.item.parentSeries`, `description.fileUnit.parentSeries`, _and_ `description.itemAv.parentSeries` (and additionally, if you want all items within a series that may belong to a file unit, you _also_ need to include `description.item.parentFileUnit.parentSeries` and `description.itemAv.parentFileUnit.parentSeries`).

**Comment by awasgreen** [comment]
Thanks so much!
