### ISSUE TITLE
RATE_LIMIT_EXCEEDED then paginate with offset > 200 

### ISSUE THREAD

**Issue by itoldya** [usnationalarchives/Catalog-API#3]
https://catalog.archives.gov/api/v1/?offset=190 - good
https://catalog.archives.gov/api/v1/?offset=191 - error

error: 
@code: "RATE_LIMIT_EXCEEDED",
description: "The estimated no. of records for the search is larger then the maximum number of records allowed to be returned for this user type: 200.",
What should we do to remove rate limits?

**Comment by MAGALY956** [comment]
Delete older version??

**Comment by DominicBM** [comment]
Sorry this was never responded to earlier, but I think this bug is now resolved. In fact, all pagination limits can now be avoided, either by only using basic paging methods up to 10,000 (not 200) results now, or by using cursor-based paging. Please check out the updated documentation!
